### ISSUE TITLE
Zły format błędów w odpowiedziach

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-backend#10]
[Die w kontrolerze](https://github.com/PZCharon/charon-backend/blob/22d43dde9222152b6341f796538f17fbef2a4c82/lib/Charon/API.pm#L42) powoduje dosłowne wysłanie odpowiedzi razem z newline'm:
```  
GET http://localhost:3000/users
{
    "message": "",
    "status": "500",
    "title": "Error 500 - Internal Server Error",
    "exception": "Login required\n"
}
```
Przez co nie możemy we froncie użyć bezpośrednio wiadomości z backendu.

**Comment by mnatan** [comment]
[Croak](https://github.com/PZCharon/charon-backend/blob/22d43dde9222152b6341f796538f17fbef2a4c82/lib/Charon/Users.pm#L57) natomiast podaje mi nazwę pliku i linię:
```
$VAR1 = {
          'title' => 'Error 500 - Internal Server Error',
          'exception' => 'Invalid name format at /home/natan/repos/charon/backend/bin/../lib/Charon/API.pm line 27.
',
          'status' => '500',
          'message' => ''
        };

```

**Comment by mnatan** [comment]
Jeszcze jedna uwaga  - ponieważ wiadomości te będziemy prezentować użytkownikowi, muszą być one w języku polskim.

**Comment by s-nez** [comment]
Duplikat #2 . Lokalizacja to problem na oddzielną dyskusję.
