### ISSUE TITLE
Obsługa wewnętrznych błędów backendu

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-backend#2]
Biblioteki backendowe powinny w jakiś w miarę ujednolicony sposób sygnalizować błędy, tak, żeby mógł powstać ogólny kod konwertujący je na odpowiednie statusy w serwerze backendowym.

**Comment by s-nez** [comment]
# Pomysł \#1:

Błędy wewnętrzne będą rzucane croak/die, łapane przez hook on_route_exception i zapisywane do logów. W zwrotce będzie tylko informacje, że wystąpił wewnętrzny błąd serwera i id loga.

Błędy przeznaczone do wyświetlania użytkownikowi będą sygnalizowane przez zwracanie w bibliotekach przestrzeni nazw Charon:: obiektów Charon::Error zamiast odpowiednich struktur danych. Hook after będzie sprawdzał, czy zwracana struktura to Charon::Error, czy nie. Jeśli nie - puszcza wszystko dalej normalnie, jeśli to Charon::Error, przekazuje mu parametr lang sesji i wyciąga odpowiednią informację do użytkownika.

## Struktura Charon::Errror

Kontruktor przyjmuje rodzaj błedu np. "no_user" lub "invalid_field_format" i pola, które trzeba wypełnić w wiadomości dla użytkownika (np. nazwa użytkownika, oczekiwany format pola, itp.).

Obiekt posiada metodę budująca wiadomość, (powiedzmy 'render'), która przyjmuje opcjonalny argument języka (domyślnie wybiera angielski). Wywołanie render na obiekcie wyciągnęło by z konfiguracji języków szablon wiadomości i wstawiło do niego odpowiednie wartości.

Przykładowa struktura:
```perl
{
    no_user => {
        pl => 'Użytkownik "%s" nie istnieje',
        en => 'No such user: "%s"',
    },
}
```
Proces budowania błędu:
```perl
my $error = Charon::Error->new('no_user', 'mark@wat.com');
print $error->render('pl');
```
Oczekiwany wynik:
```
Użytkownik "mark@wat.com" nie istnieje
```

**Comment by mnatan** [comment]
Komentarze i pytania do Pomysłu 1:

> W zwrotce będzie tylko informacja, że wystąpił wewnętrzny błąd serwera i id loga.

Jak dokładnie będzie wyglądał JSON zwracany przez REST API? Jak użytkownik API ma wywołać `render` nie mając dostępu do wewnętrznego błędu ani logów?

> Przykładowa struktura

Struktura jest dobra, ale proponuję trzymać ją w YAMLu w folderze configs. Będzie wtedy wygodniejsza w czytaniu i edycji:
```
no_user:
    pl: Użytkownik "%s" nie istnieje
    en: No such user: "%s"
```

Dodatkowo frontend i backend będą używały tego samego systemu do obsługi błędów, więc dobrze byłoby żeby miały dostęp do tej samej wersji kodu. Utworzyłem na to issue [charon12](https://github.com/PZCharon/charon/issues/12).

**Comment by s-nez** [comment]
> Jak dokładnie będzie wyglądał JSON zwracany przez REST API? Jak użytkownik API ma wywołać render nie mając dostępu do wewnętrznego błędu ani logów?

Użytkownik REST API nie wywołuje render, render wywołuje backend przed zwróceniem odpowiedzi użytkownikowi. Użytkownik dostaje tyko gotową wiadomość.

> Struktura jest dobra, ale proponuję trzymać ją w YAMLu w folderze configs

Nic nie wspominałem o sposobie przechowywaniu struktury, YAML jest ok.

**Comment by mnatan** [comment]
Ok, zatem propozycja jest dobra i uważam że powinniśmy zabrać się za implementację.

**Comment by s-nez** [comment]
W przypadku błędu wyświetlają się już odpowiednie informacje, obsługiwane są też dwa języki (polski i angielski) kontrolowane przez parametr lang w zapytaniu (przy braku parametru domyślny jest angielski).
