### ISSUE TITLE
Zmiana charsetu w bazie danych

### ISSUE THREAD

**Issue by ovk6** [PZCharon/charon-backend#20]
Po stworzeniu nowego schematu bazy danych i migracji pojawia się taki bląd:

DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at /home/olga/charon/charon-backend/bin/../lib/Database/Migration.pm line 243.

**Comment by s-nez** [comment]
Nie jestem w stanie tego odtworzyć. Czy problem nadal występuje z najnowszą wersją develop?

**Comment by ovk6** [comment]
Problem rozwiązano.
