### ISSUE TITLE
GET /students/:id

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-backend#21]
Obecnie widzę w API.pm, że mogę wykonać GET /directors/1, niestety nie ma udostępnionej żadnej takiej funkcji dla Studenta.

**Comment by s-nez** [comment]
Zaimplementowane w 07c3766073c9b329b090063cd8ccf8e5b1988299

**Comment by mnatan** [comment]
Mam problem z tym zapytaniem. Pytam tak:
`GET /students/4?token=139e531b9057994e1e048dd874fce5fa&userid=4`
i dostaję
Error 404 - Not Found

**Comment by s-nez** [comment]
Nie mogę tego odtworzyć.

**Comment by mnatan** [comment]
Odświeżyłem sobie workspace, teraz dostaję 500, więc funkcja jest wywoływana, jednak występuje error:
`[2016-09-04 13:10:25] 7 ERR: Undefined subroutine &Charon::Data::Students::get called at /app/bin/../lib/Charon/API.pm line 57.`

**Comment by mnatan** [comment]
ok, fixed: zapomniałeś:
`use Charon::Data::Students;`
