### ISSUE TITLE
API dla frontendu

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-backend#7]
Najnowszą wersję api używanego przez frontend można zobaczyć w [pliku konfiguracyjnym systemu mockowania backendu](https://github.com/PZCharon/charon-frontend/blob/develop/configs/mocks.yml).

Dostosuję się do kluczy w zwracanych haszach. Tak będzie łatwiej ustalić co dokładnie jest nam potrzebne.

Ogólne:
- [ ] GET /registrations -> lista haszy z dostępnymi rejestracjami.

Logowanie i rejestracja:
- [x] GET /user/:email -> zwraca hasz z danymi użytkownika.
- [x] POST /authorize -> email i hasło w parametrach, zwraca info czy udało się autoryzować.
- [x] POST /deauth -> przyjmuje token, pozwala zniszczyć sesję.
- [x] POST /register -> dane w parametrach, zwraca info czy udało się zarejestrować, jeśli nie to error z informacją wyświetlaną userowi.

**Comment by s-nez** [comment]
Z /registrations bym się na razie wstrzymał, bo nie wiadomo jaka dokładnie będzie struktura informacji o kierunkach i rejestracjach. Reszta jako tako zaimplementowana, żeby można było przetestować komunikację frontend-backend.

Przez "jako tako" rozumiem:
* zapytania nie są cache'owane
* tokeny nie wygasają
* wszystkie błędne zapytania powodują na razie 505
* tylko /users wymaga zalogowania

**Comment by mnatan** [comment]
GET /user/:email powinien zwracać dodatkowe pola z bazy:
- [ ] role - frontend musi wiedzieć czy ma do czynienia z adminem żeby rysować odpowiednie submenu

**Comment by s-nez** [comment]
Nie jestem pewien, czy adminów chcemy mieszać z użytkownikami w ten sposób. Zostawmy to na razie i traktuj wszystkich użytkowników jako kandydatów (możliwe, że zmienimy nazwę). Admini mają tylko i wyłącznie zarządzać innymi użytkownikami, więc powinni mieć swój własny panel, a nie jakiś dodatek w systemie dla kandydatów (admin nie zapisuje się na studia). Do tego, admini nie będą mieli wpisanych danych osobistych jak kandydaci, więc będą w oddzielnej strukturze na poziomie bazy danych.

**Comment by s-nez** [comment]
Zamiast jednego wielkiego issue na wszystko, co jest związane z API, będą oddzielne na każde wymaganie/problem.
