### ISSUE TITLE
Sesja logowania w backendzie

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-backend#8]
Sesja użytkownika jest obecnie przechowywana we frontendzie. Jednak gdybyśmy uruchomili dwie instancje frontend serwera (dla load balancingu) takie rozwiązanie spowoduje że użytkownik będzie przypadkowo wylogowywany w zależności od tego który front go obecnie obsługuje.

Z tego powodu musimy przemyśleć jak rozwiązać przechowywanie takiej sesji w backendzie, tak aby użytkownik mógł utrzymać sesję niezależnie od używanego frontendu.

Bonus: załóżmy 1 bazę danych, 2 backendy, 2 frontendy, 2 zalogowanych userów. Jak zachować sesje w sytuacji gdy użytkownicy wymienią się serwerami frontendowymi?

Ten wątek polega na zrobieniu rozeznania, wybraniu rozwiązania i implementacji.

**Comment by s-nez** [comment]
Proponuję następujące rozwiązanie:

Żeby dobrać się do zasobów wymagających autoryzacji trzeba przesłać w żądaniu token autoryzacyny sesji. Token można uzyskać przez żądanie z loginem i hasłem na np. /auth, w przypadku pomyślnej autoryzacji w zwrotce z backendu będzie token. Token można zapisać np. w cookie, wtedy jak w międzyczasie zmieni się serwer frontowy to cookie w przeglądarce użytkownika dalej będzie miało ten sam token.

Ze strony backendu widzę to tak, że tokeny aktywnych sesji będą przechowywane w bazie. Przy próbie autoryzacji wynik trafia do cache, dzięki temu kolejne zapytania od tego samego użytkownika nie będą powodowały kolejnych zapytań do bazy. Jeśli w międzyczasie ta sama sesja trafi do innego serwera backendowego, serwer ten wykona pojedyncze zapytanie do bazy i potem będzie już obsługiwał zapytania korzystając z cache.

Zostaje jeszcze kwestia terminu ważności tokenów i czyszczenie cache, ale to są szczegóły implementacyjne do ustalenia.

**Comment by mnatan** [comment]
Podoba mi się to rozwiązanie. Uważam że powinniśmy spróbować zaimplementować to na spotkanie z romanem 01.04.2016.

**Comment by s-nez** [comment]
> Ten wątek polega na zrobieniu rozeznania, wybraniu rozwiązania i implementacji.

Rozwiązanie zostało wybrane i powstała podstawowa implementacja.
