### ISSUE TITLE
Propozycja: pozbycie się charon-paths.sh

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-backend#9]
Skrypt ten wymaga użycia basha i jedyne co robi to export katalogu z programem. Nie lepiej zdobyć tę informację [w ten sposób](https://github.com/PZCharon/charon-frontend/blob/26900ac02136ad14a6c0cea21d28e4a88c733cb3/lib/CharonFront/App.pm#L19)?

**Comment by s-nez** [comment]
bin/charon.psgi już tak robi, więc przy uruchamianiu całego backendu nie trzeba używać charon-paths. Przydaje się za to do testów.
